name: Build Windows Executable

on:
   push:
     branches:
       - master
   pull_request:
     branches:
       - master

jobs:
   build-windows:
     runs-on: windows-latest

     steps:
       - name: Checkout repository
         uses: actions/checkout@v2

       - name: Set up Python
         uses: actions/setup-python@v2
         with:
           python-version: '3.9'

       - name: Install dependencies
         run: |
           python -m pip install --upgrade pip
           pip install pyinstaller
           pip install -r requirements.txt

       - name: Build executable
         run: pyinstaller --onefile main.py --add-data "C:\\hostedtoolcache\\windows\\Python\\3.9.13\\x64\\Lib\\site-packages\\emoji\\unicode_codes\\emoji.json;emoji/unicode_codes"

       - name: Generate release tag
         id: tag
         run: |
           echo "::set-output name=release_tag::Windows_$(date +"%Y.%m.%d_%H-%M")"

       - name: Create Release Tag
         shell: pwsh
         run: |
           $version = "${{ steps.tag.outputs.release_tag }}"
           git config --global user.name "github-actions"
           git config --global user.email "actions@github.com"
           git tag $version
           git push origin $version
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

       - name: Upload Release Asset
         uses: softprops/action-gh-release@v1
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
           tag_name: ${{ steps.tag.outputs.release_tag }}
           files: dist/main.exe